### ISSUE TITLE
Review Courses chapter

### ISSUE THREAD

**Issue by AshleighNovak** [thefaylab/lab-manual#14]
@ahart1 can you please review this chapter? Thanks!

**Comment by ahart1** [comment]
What is the course number for  Marine Resource Economics and BioStats I these numbers are currently  missing?

Under the "Year 1" section I tried to define what [C] vs. [PC] meant but I may have gotten it wrong.

You provide several links to SMAST/UMassD resources outlining curent core class options, ect. I would recommend listing the date that these resources are current (e.g. "Full list of current SMAST courses  **(as of 6/1/20)** and for which courses meet IMS core course...")

No instructor is listed for Chemical Oceanography, was this intentional?

Under the "Courses outside of UMass Dartmouth" section it may be worth providing a short list of courses SMAST students have taken at other UMass campuses in the past (mainly Biological and Chemical Oceanography). I believe a short list is provided on the IMS website that you could copy but is probably a bit out of date (instructors have changed) so I would just make it clear that the list is an example.

**Comment by gavinfay** [comment]
Thanks Amanda. I reviewed your pull request and suggested some changes.

The course list you reference is the table put together as part of my curriculum survey for the AQAD review. We know it is incomplete and simply reflects responses by faculty - so if no entry exists for a given course no response was given. This is a good placeholder in the meantime until a more complete version of this table is published on the SMAST website.

I like the core course denotion, also agree good to provide links to the (where available) IMS courses at other campuses.

**Comment by gavinfay** [comment]
Thanks @ahart1  for making changes to the pull request. This is now merged and am closing.
