### ISSUE TITLE
Review Lab Culture chapter 

### ISSUE THREAD

**Issue by AshleighNovak** [thefaylab/lab-manual#16]
@rwildermuth can you review the Lab Culture chapter? Thanks!

**Comment by rwildermuth** [comment]
Under "Come prepared to be engaged," I think we could add "Be present (physically/technologically and mentally)." Also, I think the last sentence could be rephrased: "Try to consider how meetings can contribute something new to your work and productivity, rather than keeping you from them."

Under "Sustain a positive, safe learning environment," this may be a good place to express that we understand that not everyone learns in the same mode (text, numbers, drawings, etc.) and that we can learn how to adapt to the modalities of our lab members.

Under "Foster inclusivity within our group and greater community," this might be a good place to (re)state that we prioritize the safety of marginalized people over the comfort of the privileged majority.

**Comment by gavinfay** [comment]
Thanks Robert for reviewing and your suggestions.
For 1) I adjusted the final sentence. I think the first part of your comment is addressed by "come ready to do your work".
2) I added text recognizing that people learn in different ways.
3) I think this bullet is getting at something different from your comment (i.e. we are emphasizing our group's 'citizenship' rather than interaction and conduct). The text you refer to is important, but I think it is in it's right place in the code of conduct.
